version: '3'

services:
  phoenix:
    container_name: server
    build: .
    environment:
      PGUSER: postgres
      PGPASS: postgres
      PGDBNAME: foodplan
      PGPORT: 5432
      PGHOST: db
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    depends_on:
      - db
  
  db:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
