version: '3'

services:
  phoenix:
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASS: postgres
      PGDATABASE: foodplan
      PGPORT: 5432
      PGHOST: db
    ports:
      - '4000:4000'
    depends_on:
      - db
  
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PG_DATA: /var/lib/postgresql/data

volumes:
  pgdata:
